// URL Encoder Constants
export const URL_SAMPLE_TEXTS = {
  SIMPLE_URL: 'https://example.com/search?q=hello world',
  COMPLEX_URL: 'https://example.com/api/users?name=Ali Valiyev&age=30&city=Toshkent',
  QUERY_STRING: 'search?q=react+hooks&type=tutorial&lang=uz',
  EMAIL_QUERY: 'mailto:ali@example.com?subject=Salom&body=Qanday ahvolingiz?',
  SOCIAL_SHARE: 'https://twitter.com/intent/tweet?text=Assalomu alaykum&url=https://webiston.uz',
}

// File processing constants
export const PROCESSING_LIMITS = {
  MAX_FILE_SIZE: 10 * 1024 * 1024, // 10MB
  MAX_TEXT_LENGTH: 1000000, // 1M characters
  TIMEOUT_DURATION: 30000, // 30 seconds
}

// URL validation patterns
export const URL_PATTERNS = {
  HTTP_URL: /^https?:\/\/.+/,
  EMAIL: /^mailto:.+/,
  PROTOCOL: /^[a-z][a-z0-9+.-]*:/,
  DOMAIN: /^[a-zA-Z0-9][a-zA-Z0-9-]{1,61}[a-zA-Z0-9]\.[a-zA-Z]{2,}$/,
}

// Common encoding examples
export const ENCODING_EXAMPLES = [
  {
    original: 'Hello World!',
    encoded: 'Hello%20World%21',
    description: "Bo'shliq va maxsus belgilar",
  },
  {
    original: 'user@example.com',
    encoded: 'user%40example.com',
    description: 'Email manzil',
  },
  {
    original: 'price=$100&tax=5%',
    encoded: 'price%3D%24100%26tax%3D5%25',
    description: 'Query parametrlari',
  },
  {
    original: 'search?q=react+hooks',
    encoded: 'search%3Fq%3Dreact%2Bhooks',
    description: "Qidiruv so'rovi",
  },
]

export const TOOL_CONSTANTS = {
  'base64-converter': {
    category: 'converters',
    featured: true,
    premium: false,
  },
  'url-encoder': {
    category: 'converters',
    featured: true,
    premium: false,
  },
  'color-converter': {
    category: 'converters',
    featured: true,
    premium: false,
  },
  'jwt-decoder': {
    category: 'converters',
    featured: true,
    premium: false,
  },
  'json-formatter': {
    category: 'utilities',
    featured: true,
    premium: false,
  },
  'hash-generator': {
    category: 'generators',
    featured: true,
    premium: false,
  },
  'password-generator': {
    category: 'generators',
    featured: true,
    premium: false,
  },
  'qr-generator': {
    category: 'generators',
    featured: true,
    premium: false,
  },
  'uuid-generator': {
    category: 'generators',
    featured: true,
    premium: false,
  },
  'lorem-ipsum': {
    category: 'generators',
    featured: true,
    premium: false,
  },
  'latin-cyrillic': {
    category: 'converters',
    featured: true,
    premium: false,
  },
} as const

// Lorem Ipsum Constants
export const LOREM_WORDS = [
  'lorem',
  'ipsum',
  'dolor',
  'sit',
  'amet',
  'consectetur',
  'adipiscing',
  'elit',
  'sed',
  'do',
  'eiusmod',
  'tempor',
  'incididunt',
  'ut',
  'labore',
  'et',
  'dolore',
  'magna',
  'aliqua',
  'enim',
  'ad',
  'minim',
  'veniam',
  'quis',
  'nostrud',
  'exercitation',
  'ullamco',
  'laboris',
  'nisi',
  'aliquip',
  'ex',
  'ea',
  'commodo',
  'consequat',
  'duis',
  'aute',
  'irure',
  'in',
  'reprehenderit',
  'voluptate',
  'velit',
  'esse',
  'cillum',
  'fugiat',
  'nulla',
  'pariatur',
  'excepteur',
  'sint',
  'occaecat',
  'cupidatat',
  'non',
  'proident',
  'sunt',
  'culpa',
  'qui',
  'officia',
  'deserunt',
  'mollit',
  'anim',
  'id',
  'est',
  'laborum',
  'at',
  'vero',
  'eos',
  'accusamus',
  'accusantium',
  'doloremque',
  'laudantium',
  'totam',
  'rem',
  'aperiam',
  'eaque',
  'ipsa',
  'quae',
  'ab',
  'illo',
  'inventore',
  'veritatis',
  'et',
  'quasi',
  'architecto',
  'beatae',
  'vitae',
  'dicta',
  'sunt',
  'explicabo',
  'nemo',
  'ipsam',
  'voluptatem',
  'quia',
  'voluptas',
  'aspernatur',
  'aut',
  'odit',
  'fugit',
  'sed',
  'quia',
  'consequuntur',
  'magni',
  'dolores',
  'ratione',
  'sequi',
  'nesciunt',
  'neque',
  'porro',
  'quisquam',
  'dolorem',
  'adipisci',
  'numquam',
  'eius',
  'modi',
  'tempora',
  'incidunt',
  'magnam',
  'quaerat',
]

export const ALTERNATIVE_TEXTS = {
  cicero: {
    name: 'Cicero (Klasik)',
    words: LOREM_WORDS,
  },
  bacon: {
    name: 'Bacon Ipsum',
    words: [
      'bacon',
      'ipsum',
      'dolor',
      'amet',
      'hamburger',
      'leberkas',
      'beef',
      'ribs',
      'brisket',
      'tongue',
      'spare',
      'ribs',
      'jerky',
      'corned',
      'beef',
      'pig',
      'short',
      'loin',
      'chicken',
      'turkey',
      'pork',
      'belly',
      'shoulder',
      'chuck',
      'sirloin',
      'bresaola',
      'pancetta',
      'meatball',
      'fatback',
      'strip',
      'steak',
      'salami',
      'capicola',
      'tail',
      'ball',
      'tip',
      'drumstick',
      'tri-tip',
      'sausage',
      'ground',
      'round',
      'pastrami',
      'shank',
      'flank',
      'kielbasa',
    ],
  },
  hipster: {
    name: 'Hipster Ipsum',
    words: [
      'artisan',
      'sustainable',
      'organic',
      'locavore',
      'craft',
      'beer',
      'quinoa',
      'kale',
      'chips',
      'beard',
      'mustache',
      'vintage',
      'retro',
      'authentic',
      'artisanal',
      'small',
      'batch',
      'farm',
      'to',
      'table',
      'fixie',
      'bicycle',
      'vinyl',
      'record',
      'player',
      'messenger',
      'bag',
      'flannel',
      'shirt',
      'skinny',
      'jeans',
      'coffee',
      'shop',
      'bookstore',
      'thrift',
      'store',
      'urban',
      'farming',
      'kombucha',
      'meditation',
      'yoga',
      'minimalist',
    ],
  },
  cupcake: {
    name: 'Cupcake Ipsum',
    words: [
      'cupcake',
      'ipsum',
      'dolor',
      'sit',
      'amet',
      'chocolate',
      'cake',
      'lemon',
      'drops',
      'pastry',
      'carrot',
      'cake',
      'gummies',
      'sweet',
      'roll',
      'danish',
      'jujubes',
      'donut',
      'candy',
      'canes',
      'apple',
      'pie',
      'cheesecake',
      'brownie',
      'cotton',
      'candy',
      'macaroon',
      'bonbon',
      'tart',
      'biscuit',
      'wafer',
      'liquorice',
      'tiramisu',
      'powder',
      'jelly',
      'beans',
      'marzipan',
      'croissant',
      'pudding',
      'fruitcake',
      'ice',
      'cream',
      'shortbread',
    ],
  },
  uzbek: {
    name: "O'zbek Lorem",
    words: [
      'matn',
      'sahifa',
      'dizayn',
      'web',
      'dasturlash',
      'loyiha',
      'ishlab',
      'chiqish',
      'texnologiya',
      'zamonaviy',
      'tizim',
      'platforma',
      'mobil',
      'ilovalar',
      'foydalanuvchi',
      'interfeys',
      'tajriba',
      'dizayner',
      'dasturchi',
      'muhandis',
      'kreativ',
      'innovatsiya',
      'raqamli',
      'dunyosi',
      'internet',
      'tarmoq',
      'malumot',
      'bazasi',
      'server',
      'bulut',
      'xavfsizlik',
      'optimizatsiya',
      'samaradorlik',
      'tezlik',
      'chiroyli',
      'zamonaviy',
      'professional',
      'mukammal',
      'ajoyib',
      'qiziqarli',
    ],
  },
}

export const LOREM_SAMPLE_SETTINGS = {
  generationType: 'paragraphs' as const,
  amount: 3,
  textType: 'cicero',
  startWithLorem: true,
}

export type LoremSettings = {
  generationType: 'paragraphs' | 'sentences' | 'words' | 'bytes'
  amount: number
  textType: string
  startWithLorem: boolean
}
